- name: Install MariaDB
  apt:
    name: mariadb-server
- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
- name: Create user on DB
  mysql_user: login_user=root login_password=root name=usterix password=usterix123 priv=*.*:ALL state=present
